name: Showcase action
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print content of index.html
        run: cat index.html
