name: If Demo
on:
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run only if
        if: github.ref_name == 'develop'
        run: echo "Main step is running"
      - name: Run this step
        run: echo "Last step is running"
